# Generated by Django 4.2.4 on 2023-08-30 14:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appPainel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('etapa', models.TextField(default='teste')),
                ('etapa_cd', models.CharField(max_length=4)),
                ('tipo', models.CharField(choices=[('AÇÃO', 'AÇÃO'), ('AQUISIÇÃO', 'AQUISIÇÃO'), ('OBRA', 'OBRA'), ('PROGRAMA', 'PROGRAMA'), ('PROJETO DE LEI', 'PROJETO DE LEI'), ('PROJETO TÉCNICO', 'PROJETO TÉCNICO'), ('OUTROS', 'OUTROS')], max_length=255)),
                ('tema', models.TextField()),
                ('descricao', models.TextField()),
                ('populacao', models.IntegerField()),
                ('iniciativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPainel.iniciativa')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPainel.responsavel')),
            ],
        ),
        migrations.AlterField(
            model_name='historicalmonitoramento',
            name='link_fotos',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalmonitoramento',
            name='link_repositorio',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='link_fotos',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='link_repositorio',
            field=models.URLField(max_length=500),
        ),
        migrations.CreateModel(
            name='MonitoramentoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CANCELADA', 'CANCELADA'), ('CONCLUÍDA', 'CONCLUÍDA'), ('EM EXECUÇÃO', 'EM EXECUÇÃO'), ('EM FORMULAÇÃO', 'EM FORMULAÇÃO'), ('EM LICITAÇÃO', 'EM LICITAÇÃO'), ('LICITAÇÃO CONCLUÍDA', 'LICITAÇÃO CONCLUÍDA'), ('PARALISADA', 'PARALISADA'), ('PROJETO TÉCNICO EM ELABORAÇÃO', 'PROJETO TÉCNICO EM ELABORAÇÃO'), ('SUSPENSA', 'SUSPENSA')], max_length=255)),
                ('data_inicio_planejado', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio_atualizado', models.DateTimeField(blank=True, null=True)),
                ('data_termino_planejado', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_termino_atualizado', models.DateTimeField(blank=True, null=True)),
                ('execucao_fisica', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observacao', models.TextField()),
                ('link_fotos', models.URLField(max_length=500)),
                ('link_repositorio', models.URLField(max_length=500)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPainel.etapa')),
            ],
            options={
                'verbose_name_plural': 'Monitoramento',
                'ordering': ('etapa',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalMonitoramentoEtapa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('CANCELADA', 'CANCELADA'), ('CONCLUÍDA', 'CONCLUÍDA'), ('EM EXECUÇÃO', 'EM EXECUÇÃO'), ('EM FORMULAÇÃO', 'EM FORMULAÇÃO'), ('EM LICITAÇÃO', 'EM LICITAÇÃO'), ('LICITAÇÃO CONCLUÍDA', 'LICITAÇÃO CONCLUÍDA'), ('PARALISADA', 'PARALISADA'), ('PROJETO TÉCNICO EM ELABORAÇÃO', 'PROJETO TÉCNICO EM ELABORAÇÃO'), ('SUSPENSA', 'SUSPENSA')], max_length=255)),
                ('data_inicio_planejado', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio_atualizado', models.DateTimeField(blank=True, null=True)),
                ('data_termino_planejado', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_termino_atualizado', models.DateTimeField(blank=True, null=True)),
                ('execucao_fisica', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observacao', models.TextField()),
                ('link_fotos', models.URLField(max_length=500)),
                ('link_repositorio', models.URLField(max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('etapa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.etapa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical monitoramento etapa',
                'verbose_name_plural': 'historical Monitoramento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEtapa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('etapa', models.TextField(default='teste')),
                ('etapa_cd', models.CharField(max_length=4)),
                ('tipo', models.CharField(choices=[('AÇÃO', 'AÇÃO'), ('AQUISIÇÃO', 'AQUISIÇÃO'), ('OBRA', 'OBRA'), ('PROGRAMA', 'PROGRAMA'), ('PROJETO DE LEI', 'PROJETO DE LEI'), ('PROJETO TÉCNICO', 'PROJETO TÉCNICO'), ('OUTROS', 'OUTROS')], max_length=255)),
                ('tema', models.TextField()),
                ('descricao', models.TextField()),
                ('populacao', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('iniciativa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.iniciativa')),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.responsavel')),
            ],
            options={
                'verbose_name': 'historical etapa',
                'verbose_name_plural': 'historical etapas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
