# Generated by Django 4.2.4 on 2023-09-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPainel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='etapa_cd',
            field=models.CharField(max_length=4, unique=True, verbose_name='Código da Etapa'),
        ),
        migrations.AlterField(
            model_name='historicaletapa',
            name='etapa_cd',
            field=models.CharField(db_index=True, max_length=4, verbose_name='Código da Etapa'),
        ),
        migrations.AlterField(
            model_name='historicaliniciativa',
            name='iniciativa_cd',
            field=models.CharField(db_index=True, max_length=4, verbose_name='Código da Iniciativa'),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='iniciativa_cd',
            field=models.CharField(max_length=4, unique=True, verbose_name='Código da Iniciativa'),
        ),
    ]
