# Generated by Django 4.2.4 on 2023-11-17 17:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPainel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmonitoramentoetapa',
            name='meta',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.meta', verbose_name='Nome da Meta'),
        ),
        migrations.AddField(
            model_name='monitoramentoetapa',
            name='meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appPainel.meta', verbose_name='Nome da Meta'),
        ),
        migrations.AlterField(
            model_name='historicalmonitoramento',
            name='execucao_fisica',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Execução Física'),
        ),
        migrations.AlterField(
            model_name='historicalmonitoramentoetapa',
            name='execucao_fisica',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Execução Física'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='execucao_fisica',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Execução Física'),
        ),
        migrations.AlterField(
            model_name='monitoramentoetapa',
            name='execucao_fisica',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Execução Física'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='renda_per_capta',
            field=models.FloatField(default=0, verbose_name='PIB per Capita'),
        ),
    ]
