# Generated by Django 4.2.4 on 2023-11-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPainel', '0002_historicalmonitoramentoetapa_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmonitoramentosubetapa',
            name='etapa',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.etapa', verbose_name='Nome da Etapa'),
        ),
        migrations.AddField(
            model_name='monitoramentosubetapa',
            name='etapa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appPainel.etapa', verbose_name='Nome da Etapa'),
        ),
        migrations.AlterField(
            model_name='historicalmonitoramentoetapa',
            name='meta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.meta', verbose_name='Nome da Meta'),
        ),
        migrations.AlterField(
            model_name='monitoramentoetapa',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPainel.meta', verbose_name='Nome da Meta'),
        ),
    ]
