# Generated by Django 4.2.4 on 2023-11-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPainel', '0003_historicalmonitoramentosubetapa_etapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmonitoramentosubetapa',
            name='etapa',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.monitoramentoetapa', verbose_name='Nome da Etapa'),
        ),
        migrations.AlterField(
            model_name='monitoramentosubetapa',
            name='etapa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appPainel.monitoramentoetapa', verbose_name='Nome da Etapa'),
        ),
    ]
