# Generated by Django 4.2.4 on 2023-08-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPainel', '0003_municipio_historicalmunicipio_iniciativa_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmonitoramento',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical monitoramento', 'verbose_name_plural': 'historical Monitoramento Iniciativa'},
        ),
        migrations.AlterModelOptions(
            name='historicalmonitoramentoetapa',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical monitoramento etapa', 'verbose_name_plural': 'historical Monitoramento Etapa'},
        ),
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'ordering': ('iniciativa',), 'verbose_name_plural': 'Monitoramento Iniciativa'},
        ),
        migrations.AlterModelOptions(
            name='monitoramentoetapa',
            options={'ordering': ('etapa',), 'verbose_name_plural': 'Monitoramento Etapa'},
        ),
        migrations.AddField(
            model_name='etapa',
            name='municipio',
            field=models.ManyToManyField(default='Recife', to='appPainel.municipio'),
        ),
    ]
