# Generated by Django 4.2.4 on 2023-12-04 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPainel', '0004_alter_historicalmonitoramentosubetapa_etapa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmonitoramentosubetapa',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='monitoramentosubetapa',
            name='etapa',
        ),
        migrations.AlterField(
            model_name='historicalmonitoramentosubetapa',
            name='subetapa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.subetapa', verbose_name='Meta | Etapa | Subetapa'),
        ),
        migrations.AlterField(
            model_name='monitoramentosubetapa',
            name='subetapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPainel.subetapa', verbose_name='Meta | Etapa | Subetapa'),
        ),
    ]
