# Generated by Django 4.2.4 on 2024-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPainel', '0003_historicalmonitoramentosubetapa_etapa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eixo',
            options={'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivo Estratégico'},
        ),
        migrations.AlterModelOptions(
            name='historicaleixo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Objetivo', 'verbose_name_plural': 'historical Objetivo Estratégico'},
        ),
        migrations.AlterField(
            model_name='eixo',
            name='eixo_estrategico',
            field=models.CharField(max_length=255, verbose_name='Nome do Objetivo'),
        ),
        migrations.AlterField(
            model_name='eixo',
            name='eixo_estrategico_cd',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código do Objetivo'),
        ),
        migrations.AlterField(
            model_name='historicaleixo',
            name='eixo_estrategico',
            field=models.CharField(max_length=255, verbose_name='Nome do Objetivo'),
        ),
        migrations.AlterField(
            model_name='historicaleixo',
            name='eixo_estrategico_cd',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Código do Objetivo'),
        ),
    ]
