# Generated by Django 4.2.4 on 2024-01-22 18:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appPainel', '0006_alter_eixo_options_alter_historicaleixo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.CharField(max_length=255, verbose_name='Tipo')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Início')),
                ('hora_termino', models.TimeField(verbose_name='Hora Término')),
                ('assunto', models.CharField(max_length=255, verbose_name='Tipo')),
                ('participante', models.ManyToManyField(to='appPainel.responsavel', verbose_name='Participante')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPainel.secretaria', verbose_name='Nome da Secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalReuniao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('politica', models.CharField(max_length=255, verbose_name='Tipo')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Início')),
                ('hora_termino', models.TimeField(verbose_name='Hora Término')),
                ('assunto', models.CharField(max_length=255, verbose_name='Tipo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.secretaria', verbose_name='Nome da Secretaria')),
            ],
            options={
                'verbose_name': 'historical reuniao',
                'verbose_name_plural': 'historical reuniaos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
