# Generated by Django 4.2.4 on 2024-01-22 21:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appPainel', '0006_alter_eixo_options_alter_historicaleixo_options_and_more'),
        ('reuniao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreuniao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reuniao', 'verbose_name_plural': 'historical Reuniões'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name_plural': 'Reuniões'},
        ),
        migrations.AlterField(
            model_name='historicalreuniao',
            name='assunto',
            field=models.CharField(max_length=255, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='historicalreuniao',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora início'),
        ),
        migrations.AlterField(
            model_name='historicalreuniao',
            name='hora_termino',
            field=models.TimeField(verbose_name='Hora término'),
        ),
        migrations.AlterField(
            model_name='historicalreuniao',
            name='numero',
            field=models.IntegerField(verbose_name='Número da reunião'),
        ),
        migrations.AlterField(
            model_name='historicalreuniao',
            name='politica',
            field=models.CharField(max_length=255, verbose_name='Política'),
        ),
        migrations.AlterField(
            model_name='historicalreuniao',
            name='secretaria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='appPainel.secretaria', verbose_name='Nome da secretaria'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='assunto',
            field=models.CharField(max_length=255, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora início'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='hora_termino',
            field=models.TimeField(verbose_name='Hora término'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='numero',
            field=models.IntegerField(verbose_name='Número da reunião'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='politica',
            field=models.CharField(max_length=255, verbose_name='Política'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPainel.secretaria', verbose_name='Nome da secretaria'),
        ),
        migrations.CreateModel(
            name='HistoricalEncaminhamento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('encaminhamento', models.TextField(verbose_name='Encaminhamento')),
                ('prazo', models.DateField(default=datetime.date.today, verbose_name='Prazo')),
                ('devolutiva', models.TextField(verbose_name='Devolutiva')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reuniao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reuniao.reuniao', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'historical encaminhamento',
                'verbose_name_plural': 'historical Encaminhamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('encaminhamento', models.TextField(verbose_name='Encaminhamento')),
                ('prazo', models.DateField(default=datetime.date.today, verbose_name='Prazo')),
                ('devolutiva', models.TextField(verbose_name='Devolutiva')),
                ('responsavel', models.ManyToManyField(to='appPainel.responsavel', verbose_name='Responsável')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.reuniao', verbose_name='Reunião')),
            ],
            options={
                'verbose_name_plural': 'Encaminhamentos',
            },
        ),
    ]
